### ISSUE TITLE
suggestion for improvement OpenTelemetry

### ISSUE THREAD

**Issue by SyntaxEvg** [zamat/zamat-clean-architecture#10]
Hi friend, it seems to me that your architecture of oblique open telemetry is not quite right, can you look at such a project and modify it for yours using storage s3
https://github.com/choiis/Grafana-Mimir-Loki-Jaeger/

**Comment by zamat** [comment]
Thanks for this right suggestion but  I'll stick with the current solution. Backend for open telemetry is not so important as using otel collector for application layer in this example case
